export enum TaxType {
    ImportDuty = 1,
    Consolidated,
    SalesTax,
    GoodsAndServicesTax,
    InputTaxed,
    LuxuryCarsTax
}

export enum AccountClassification {
    Asset = 1,
    Liability = 2,
    OwnerEquities = 3,
    Income = 4,
    Expenses = 5,
}

export enum AccountType {
    CurrentAsset = 1,
    FixedAsset = 2,
    IntangibleAsset = 3,
    ShortTermLiabilities = 4,
    LongTermLiabilities = 5,
    OperatingIncome = 6,
    NonOperatingIncome = 7,
    OperatingExpense = 8,
    NonOperatingExpense = 9
}

export enum DebitCreditIndicator {
    Debit = 1,
    Credit = 2
}

export enum ReferenceType {
    Demo = 0,
    OpeningBalance = 1,
    MoneyTransfer = 2,
    CombineAccount = 3
}

export enum Module {
    OpeningBalance = 1,
    MoneyTransfer = 2,
    CombineAccount = 3
}

export enum COA {
    Asset = 1,
    CurrentAsset,
    BankAccount1,
    BankAccount2,
    BankAccount3,
    BankAccount4,
    CashOnHand,
    PettyCash,
    ClearingAccounts,
    UndepositedFundAccount,
    ElectronicClearingAccount,
    PayrollClearingAccount,
    OtherCurrentAssets,
    AccountsReceivableOrTradeDebtors,
    Inventory,
    VoluntaryWithholdingCredits,
    ABNWithholdingCredits,
    AdvanceExpense,
    AdvanceSalary,
    AdvanceOfficeRent,
    AdvanceFuelExpense,
    AdvanceConveyance,
    ThirdPartyLoan,
    ThirdPartyLoan2,
    ThirdPartyLoanInterest,
    FurnitureAndFixture,
    Chair,
    Tables,
    Cupboards,
    ElectricEquipments,
    CeilingFan,
    Generator,
    ElectricBoard,
    OfficeEquipment,
    Calculator,
    PaperBox,
    ComputerAndOtherITEquipment,
    LaptopComputer,
    DesktopComputer,
    PowerSupply,
    Printer,
    Scanner,
    AirConditioner,
    Gree54LK20,
    Panasonic20,
    OfficeRenovation,
    Decoration,
    Shelves,
    Vehicles,
    Car,
    PickupVan,
    LandAndBuilding,
    OfficeLand,
    OfficeBuilding,
    LowValuePool,
    GoodWill,
    Liabilities,
    CurrentLiabilities,
    AccountsPayableOrTradeCreditors,
    MasterCards1,
    MasterCards2,
    VisaCards1,
    VisaCards2,
    CreditCards1,
    CreditCards2,
    AMEX1,
    AMEX2,
    DueExpense,
    DueSalary,
    DueOfficeRent,
    DueFuelExpense,
    DueConveyance,
    GSTLiabilities,
    GSTPayable,
    TaxOrWithholdingPayable,
    VoluntaryWithholdingPayable,
    CompanyTaxPayable,
    ABNWithholdingPayable,
    FBTInstallmentPayable,
    CarTaxPayable,
    SalesTaxPayable,
    PAYGWithholdingPayable,
    SuperannuationFund1,
    superannuationFund2,
    ChildCarePayable,
    UnionFeesPayable,
    OtherPayrollLiabilities,
    OwnersEquities,
    OwnersOrShareHoldersCapital,
    OwnersOrShareHoldersDrawing,
    RetainedEarnings,
    CurrentYearEarnings,
    HistoricalBalance,
    Income,
    ProductSalesIncome,
    ServiceSalesIncome,
    LateFeesCollected,
    OtherIncome,
    InterestFromThirdPartyLoan,
    BankInterest,
    DonationIncome,
    CostOfGoodsSold,
    Expense,
    GeneralExpense,
    RegistrationFees,
    ParkingExpense,
    Advertisement,
    ConveyanceBill,
    TeaBill,
    WaterBill,
    DirectorsFees,
    UniformExpense,
    StaffTraining,
    SecuritySalary,
    GasBill,
    FuelExpense,
    LateFees,
    InternetBill,
    PaperBill,
    ElectricityExpense,
    OfficeRent,
    LunchBill,
    EveningSnacks,
    BadDebts,
    CleaningExpense,
    BorrowingExpense,
    LegalFees,
    ParkingBill,
    RepairAndMaintenance,
    LicenseRenewal,
    PrintingBill,
    Stationary,
    CouncilExpense,
    Wastage,
    TelephoneBill,
    Postage,
    DiscountExpense,
    Utilities,
    DepreciationExpense,
    FurnitureAndFixtureDepreciation,
    ElectricEquipmentsDepreciation,
    OfficeEquipmentDepreciation,
    ComputerAndITEquipmentDepreciation,
    AirConditionerDepreciation,
    VehiclesDepreciation,
    BuildingsDepreciation,
    Wages,
    Salaries,
    FestivalBonus,
    YearlyBonus,
    Incentive,
    OvertimeExpense,
    VehiclesExpense,
    VehicleRegistration,
    VehicleRepairAndMaintenance,
    VehicleFuelExpense,
    VehicleInsurance,
    GarageRent,
    BusinessInsurance,
    PublicLiabilityInsurance,
    IndemnityInsurance,
    OtherExpenses,
    BankCharge,
    LoanInterest,
    IncomeTaxExpense,
    DonationExpense
}